name: Build Docker

on:
  push:
    branches: [ "main" ]
    tags:     [ "*" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  IMAGE_NAME: nixvim
  REGISTRY: ghcr.io
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Install nix
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      # build nixvim docker image
      - name: Build nixvim Docker Image (tarball)
        run: |
          nix build .#packages.x86_64-linux.docker \
            --out-link result-image
      
      # Import image to docker daemon
      - name: docker load
        run: docker load --input result-image

      # Tag image
      - name: Retag for GHCR
        id: tagstep
        env:
          OWNER: ${{ github.repository_owner }}
        run: |
          OWNER_LC=$(echo "$OWNER" | tr '[:upper:]' '[:lower:]')
          LOCAL=$(docker images --format '{{.Repository}}:{{.Tag}}' | head -1)
          SHORT_SHA=$(git rev-parse --short=8 $GITHUB_SHA)  # get truncated commit hash

          # Export varaibles for later steps
          echo "owner_lc=$OWNER_LC" >> "$GITHUB_OUTPUT"
          echo "short_sha=$SHORT_SHA" >> "$GITHUB_OUTPUT"

          docker tag "$LOCAL" $REGISTRY/${OWNER_LC}/${IMAGE_NAME}:latest
          docker tag "$LOCAL" $REGISTRY/${OWNER_LC}/${IMAGE_NAME}:$SHORT_SHA

          # if the workflow was triggered by an annotated tag (e.g. v1.0.0)
          if [ "${GITHUB_REF_TYPE}" = "tag" ]; then
            docker tag "$LOCAL" $REGISTRY/${OWNER_LC}/${IMAGE_NAME}:${GITHUB_REF_NAME}
            echo "extra_tag=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT
          fi

      # Authenticate to GHCR and push
      - name: Login & push
        env:
          OWNER_LC: ${{ steps.tagstep.outputs.owner_lc }}
          SHORT_SHA: ${{ steps.tagstep.outputs.short_sha }}
          EXTRA_TAG: ${{ steps.tagstep.outputs.extra_tag }}
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
            docker login $REGISTRY -u "${{ github.actor }}" --password-stdin
  
          docker push $REGISTRY/${OWNER_LC}/${IMAGE_NAME}:latest
          docker push $REGISTRY/${OWNER_LC}/${IMAGE_NAME}:$SHORT_SHA
  
          if [ -n "$EXTRA_TAG" ]; then
            docker push $REGISTRY/${OWNER_LC}/${IMAGE_NAME}:$EXTRA_TAG
          fi
